#%RAML 1.0
title: stephenTest

description: This is to test the sample app

/cust:
  get:
    description: This resource is used to retrieve the data.
    queryParameters:
      id:
        required: true
        example: "12345"
    responses:
      200:
        body:
          application/json:
            example:
              {
                "firstName" : "Test1",
                "lastName" : "Test2"
              }
      500:
        body:
          application/json:
            example: "Internal Server Error"

  post:
    body:
      application/json:
        example:
          {
            "firstName" : "Test3",
            "lastName" : "Test4"
          }
          
          